apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: security-gateway
spec:
  addresses:
    - type: IPAddress
      value: 10.140.79.10
  gatewayClassName: cilium
  listeners:
    - name: https-keycloak
      hostname: keycloak.inspection.alpha.canada.ca
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: keycloak.inspection.alpha.canada.ca-tls
            kind: Secret
