apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
  data:
    - secretKey: admin-password
      remoteRef:
        key: secrets/keycloak/admin-password
        property: admin-password
    - secretKey: pgsql-password
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/bn-keycloak-dev-user
        property: password
    - secretKey: pgsql-host
      remoteRef:
        key: secrets/keycloak/pgsql-host
        property: pgsql-host
