apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
  dataFrom:
    - extract:
        key: devsecops/cloudnativepg/bn-keycloak-dev-user
    - extract:
        key: devsecops/keycloak
