---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelstudio
  namespace: annotation
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: labelstudio
  template:
    metadata:
      labels:
        app: labelstudio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      initContainers:
        - name: fix-data-volume-permissions
          image: alpine:3
          command:
            - sh
            - -c
            - "chown -R 1001:1001 /label-studio/data && chmod -R 755 /label-studio/data"
          volumeMounts:
            - name: labelstudio-pvc
              mountPath: /label-studio/data
      containers:
        - name: labelstudio
          image: heartexlabs/label-studio:1.18.0
          imagePullPolicy: Always
          # command: ["label-studio-uwsgi"]
          # resources:
          #   requests:
          #     cpu: 16
          #     memory: 64Gi
          # limits:
          #   nvidia.com/gpu: 1
          ports:
            - containerPort: 8080
          tty: true
          stdin: true
          env:
            - name: JSON_LOG
              value: "1"
            - name: LABEL_STUDIO_HOST
              value: "https://labelstudio.inspection.alpha.canada.ca"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://labelstudio.inspection.alpha.canada.ca"
          envFrom:
            - secretRef:
                name: labelstudio-secrets
          volumeMounts:
            - name: labelstudio-pvc
              mountPath: /label-studio/data
            - name: labelstudio-shared-volume
              mountPath: /ailab
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SETUID
                - SETGID
                - DAC_OVERRIDE
              drop:
                - ALL_OTHERS
      volumes:
        - name: labelstudio-shared-volume
          persistentVolumeClaim:
            claimName: labelstudio-shared-pvc
        - name: labelstudio-pvc
          persistentVolumeClaim:
            claimName: labelstudio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: labelstudio-svc
spec:
  type: ClusterIP
  selector:
    app: labelstudio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
