---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: labelstudio-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: labelstudio-secrets
  dataFrom:
    - extract:
        key: secrets/annotation/labelstudio
