---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nachet-training-workspace-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ceph-hot-filesystem
  resources:
    requests:
      storage: 20Gi
