---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openssh-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: openssh-secrets
    template:
      engineVersion: v2
      data:
        authorized_keys: |
          {{ .user1_key | toString }}
          {{ .user2_key | toString }}
          {{ .user3_key | toString }}
    creationPolicy: Owner
  data:
    - secretKey: user1_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: js_pubkey
    - secretKey: user2_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: tc_pubkey
    - secretKey: user3_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: kl_pubkey
