---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openssh-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: openssh-secrets
    template:
      engineVersion: v2
      data:
        AUTHORIZED_KEYS: |
          {{ .user1_key | toString }}
          {{ .user2_key | toString }}
          {{ .user3_key | toString }}
          {{ .user4_key | toString }}
          {{ .user5_key | toString }}
          {{ .user6_key | toString }}
          {{ .user7_key | toString }}
          {{ .user8_key | toString }}
          {{ .user9_key | toString }}
          {{ .user10_key | toString }}
          {{ .user11_key | toString }}
    creationPolicy: Owner
  data:
    - secretKey: user1_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: js_pubkey
    - secretKey: user2_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: tc_pubkey
    - secretKey: user3_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: kl_pubkey
    - secretKey: user4_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: lz_pubkey
    - secretKey: user5_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: ib_pubkey
    - secretKey: user6_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: bg_pubkey
    - secretKey: user7_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: rh_pubkey
    - secretKey: user8_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: cl_pubkey
    - secretKey: user9_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: ml_pubkey
    - secretKey: user10_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: jp_pubkey
    - secretKey: user11_key
      remoteRef:
        key: secrets/ailab-shared/openssh-keys
        property: am_pubkey
