---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chromadb
  name: chromadb-pvc
spec:
  storageClassName: ceph-hot-block
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
