---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-frontend-secrets
  namespace: nachet-prod
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-frontend-secrets
  dataFrom:
    - find:
        path: secrets/nachet/azure
        name:
          regexp: ".*"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-backend-secrets
  namespace: nachet-prod
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-backend-secrets
  dataFrom:
    - find:
        path: secrets/nachet/azure
        name:
          regexp: ".*"
