---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-prod-op-secrets
  namespace: nachet-prod
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-prod-op-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/prod/backend/secret
