apiVersion: apps/v1
kind: Deployment
metadata:
  name: trufflehog-verif-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: trufflehog-verif-server
  template:
    metadata:
      labels:
        app: trufflehog-verif-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      containers:
        - name: trufflehog-verif-server
          image: ghcr.io/ai-cfia/trufflehog-verif-server:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: trufflehog-verif-server-svc
spec:
  type: ClusterIP
  selector:
    app: trufflehog-verif-server
  ports:
    - protocol: TCP
      port: 8000
