apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: memos-gateway
spec:
  addresses:
    - type: IPAddress
      value: 10.140.79.32
  gatewayClassName: cilium
  listeners:
    - name: https-memos
      hostname: memos.inspection.alpha.canada.ca
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: memos-tls
            kind: Secret
