apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: memos-secrets
  dataFrom:
    - extract:
        key: secrets/memos
