apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnativepg
  sources:
    - chart: cloudnative-pg
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $values/storage/cloudnativepg/helm/values.yaml
      repoURL: https://cloudnative-pg.io/charts/
      targetRevision: 0.26.1
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: storage/cloudnativepg/base/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
