apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnativepg
  sources:
    - repoURL: https://github.com/cloudnative-pg/artifacts/
      path: manifests
      targetRevision: main
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: storage/cloudnativepg/base/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
