apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lgtm
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - chart: lgtm-distributed
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.1.0
      helm:
        releaseName: lgtm-distributed
        valueFiles:
          - $values/monitoring/grafana-lgtm/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: monitoring/grafana-lgtm/base
      targetRevision: HEAD
