apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: acia-cfia-prod-cluster
spec:
  description: "ACIA-CFIA prod cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 md5

  managed:  
    roles:
      - name: nachet
        ensure: present
        comment: "Owner of nachet databases"
        login: true
        createdb: true
        createrole: false
        inherit: true
        replication: false
        bypassrls: false
        connectionLimit: 10
        passwordSecret:
          name: nachet-prod-user-creds

  backup:
    barmanObjectStore:
      destinationPath: s3://acia-cfia-prod-cluster-backup/
      endpointURL: http://minio-svc.minio:9000
      s3Credentials:
        accessKeyId:
          name: minio-secret-prod
          key: rootUser
        secretAccessKey:
          name: minio-secret-prod
          key: rootPassword
      wal:
        compression: gzip
      data:
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"
          - "-vv"
    retentionPolicy: "30d"

  storage:
    storageClass: ceph-hot-block
    size: 70Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: acia-cfia-prod-cluster-creds

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - app-worker
    enablePodAntiAffinity: true
