apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acia-cfia-prod-cluster-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: acia-cfia-prod-cluster-creds
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/acia-cfia-prod-cluster
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/acia-cfia-prod-cluster
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-secret-prod
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/minio
        property: minio.values

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-prod-user-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-prod-user-creds
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-prod-user
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-prod-user
        property: password
