---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fertiscan-preview-logs-pvc
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fertiscan-preview-uploads-pvc
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
