---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: litellm-secrets
  dataFrom:
    - extract:
        key: secrets/louis/litellm

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-connection-string
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: litellm-connection-string
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username | toString }}:{{ .password | toString }}@{{ .base_url | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/devsecops/cloudnativepg/litellm-dev-user
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/devsecops/cloudnativepg/litellm-dev-user
        property: password
    - secretKey: base_url
      remoteRef:
        key: secrets/devsecops/cloudnativepg/litellm-dev-user
        property: base_url
