# https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers/keycloak
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: vault-client
spec:
  providerConfigRef:
    name: keycloak-provider
  forProvider:
    accessType: CONFIDENTIAL
    name: vault
    clientId: vault
    realmIdRef:
      name: infra-realm
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    rootUrl: http://10.140.79.12/
    accessTokenLifespan: 10800  # 3 hours
    validRedirectUris:
      - http://10.140.79.12/ui/vault/auth/oidc/oidc/callback
      - http://10.140.79.12/oidc/oidc/callback

---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: minio-client
spec:
  providerConfigRef:
    name: keycloak-provider
  forProvider:
    accessType: CONFIDENTIAL
    name: minio
    clientId: minio
    realmIdRef:
      name: infra-realm
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    rootUrl: http://10.140.79.26/
    accessTokenLifespan: 10800  # 3 hours
    validRedirectUris:
      - *