apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-crossplane-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-crossplane-credentials
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/keycloak
