apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: azure-credentials
  dataFrom:
    - secretKey: cloud
      remoteRef:
        key: devsecops/velero
        property: cloud
