---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fiftyone-s3-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: fiftyone-s3-secrets
  dataFrom:
    - extract:
        key: secrets/mlflow/s3
