apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: controller-manager
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/acia-cfia-gh-runners
