---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: telepresence
    server: https://kubernetes.default.svc
  sources:
    - chart: telepresence-oss
      helm:
        valueFiles:
          - $values/gitops/telepresence/helm/values.yaml
      repoURL: ghcr.io/telepresenceio
      targetRevision: 2.24.1
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
