apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: harbor-admin-secret
    template:
      type: Opaque
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .admin_password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: admin_password
      remoteRef:
        key: secrets/harbor
        property: admin_password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-database-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: harbor-database-secret
    template:
      type: Opaque
      data:
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: devsecops/cloudnativepg/harbor-user
        property: password
