apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-deployed.github: ""
spec:
  project: default
  destination:
    namespace: librechat
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: apps/librechat/base/
      targetRevision: HEAD
