apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: mlflow-secrets
  dataFrom:
    - extract:
        key: devsecops/cloudnativepg/mlflow-user-creds
