apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: mlflow-secrets
  dataFrom:
    - extract:
        key: devsecops/cloudnativepg/mlflow-user-creds
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-s3-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secrets-store
    kind: ClusterSecretStore
  target:
    name: mlflow-s3-secrets
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secrets/mlflow/s3
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secrets/mlflow/s3
        property: AWS_SECRET_ACCESS_KEY
