apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nachet-prod-cluster-backup
spec:
  schedule: "0 0 * * 5"  # Friday midnight (UTC)
  backupOwnerReference: self
  cluster:
    name: nachet-prod-cluster
