apiVersion: v1
kind: ConfigMap
metadata:
  name: config-image-policies
data:
  policies.yaml: |
    apiVersion: policy.sigstore.dev/v1beta1
    kind: ClusterImagePolicy
    metadata:
      name: default-policy
    spec:
      images:
      - glob: "**"
        authorities:
        - keyless:
            url: https://fulcio.sigstore.dev
            identities:
            - issuer: https://token.actions.githubusercontent.com
              subject: "https://github.com/*/*"
          ctlog:
            url: https://rekor.sigstore.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "timestamp",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
data:
  _example: |
    metrics.backend-destination: prometheus
