apiVersion: v1
kind: Service
metadata:
  name: cosign-webhook
  namespace: cosign
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: cosign-webhook
