apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cosign-webhook
  annotations:
    cert-manager.io/inject-ca-from: cosign/cosign-webhook-cert
webhooks:
- name: validate.sigstore.dev
  clientConfig:
    service:
      name: cosign-webhook
      namespace: cosign
      path: /validations
    caBundle: Cg==  # Sera automatiquement mis à jour par cert-manager
  admissionReviewVersions: ["v1", "v1beta1"]
  failurePolicy: Fail
  sideEffects: None
  namespaceSelector:
    matchExpressions:
    - key: policy.sigstore.dev/include
      operator: In
      values: ["true"]
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    operations: ["CREATE", "UPDATE"]
  - apiGroups: ["batch"]
    apiVersions: ["v1"]
    resources: ["jobs", "cronjobs"]
    operations: ["CREATE", "UPDATE"]
