apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: librechat-secrets
  dataFrom:
    - extract:
        key: secrets/librechat/librechat-client
    - extract:
        key: secrets/louis/litellm

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: meilisearch-secrets
  dataFrom:
    - extract:
        key: secrets/librechat/meilisearch

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vectordb-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: vectordb-secrets
  dataFrom:
    - extract:
        key: secrets/librechat/vectordb

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rag-api-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: rag-api-secrets
  dataFrom:
    - extract:
        key: secrets/librechat/rag-api
    - extract:
        key: secrets/librechat/vectordb
    - extract:
        key: secrets/librechat/librechat-client
