apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-researcher-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gpt-researcher
  template:
    metadata:
      labels:
        app: gpt-researcher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: gpt-researcher
          image: ghcr.io/ai-cfia/louis/gpt-researcher-mcp:louis-3e891a1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gpt-researcher-secrets
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
            - name: docs-pvc
              mountPath: /usr/src/app/my-docs
      volumes:
        - name: config-volume
          configMap:
            name: gpt-researcher-config
        - name: docs-pvc
          persistentVolumeClaim:
            claimName: gpt-researcher-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpt-researcher-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-hot-block
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: gpt-researcher-service
spec:
  selector:
    app: gpt-researcher
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
