---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: on-prem-gh-runners-scaleset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: on-prem-gh-runners
    server: https://kubernetes.default.svc
  sources:
    - chart: gha-runner-scale-set
      helm:
        valueFiles:
          - $values/gitops/on-prem-gh-runners-scaleset/helm/values.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.10.1
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
