---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: on-prem-gh-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: on-prem-gh-runners
    server: https://kubernetes.default.svc
  sources:
    - chart: gha-runner-scale-set-controller
      helm:
        valueFiles:
          - $values/gitops/on-prem-gh-runners/helm/values.controller.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.11.0
    - chart: gha-runner-scale-set
      helm:
        valueFiles:
          - $values/gitops/on-prem-gh-runners/helm/values.scaleset.yaml
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.12.0
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: gitops/on-prem-gh-runners/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
