# helm-docs renders these comments into markdown. Use markdown formatting where
# appropiate.
#
# -- The number of Crossplane pod `replicas` to deploy.
replicas: 1

# -- The number of Crossplane ReplicaSets to retain.
revisionHistoryLimit: 3

# -- The deployment strategy for the Crossplane and RBAC Manager pods.
deploymentStrategy: RollingUpdate

image:
  # -- Repository for the Crossplane pod image.
  repository: xpkg.upbound.io/upbound/crossplane
  # -- The Crossplane image tag. Defaults to the value of `appVersion` in `Chart.yaml`.
  tag: "v1.19.0-up.1"
  # -- The image pull policy used for Crossplane and RBAC Manager pods.
  pullPolicy: IfNotPresent

# -- Add `affinities` to the Crossplane pod deployment.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - app-worker

provider:
  # -- A list of Provider packages to install.
  packages: ["xpkg.upbound.io/crossplane-contrib/provider-keycloak:v2.0.0", "xpkg.upbound.io/upbound/provider-vault:v2.1.1"]

configuration:
  # -- A list of Configuration packages to install.
  packages: []

function:
  # -- A list of Function packages to install
  packages: []

resourcesCrossplane:
  limits:
    # -- CPU resource limits for the Crossplane pod.
    cpu: 500m
    # -- Memory resource limits for the Crossplane pod.
    memory: 1024Mi
  requests:
    # -- CPU resource requests for the Crossplane pod.
    cpu: 100m
    # -- Memory resource requests for the Crossplane pod.
    memory: 256Mi
