apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ragflow-env-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: ragflow-env-config
  dataFrom:
    - extract:
        key: secrets/ragflow
        property: ragflow.values
