apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-secret
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/minio
        property: minio.values

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-client-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-client-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: minio-client-secret
      remoteRef:
        key: secrets/keycloak
        property: minio-client-secret
