apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-secret
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/minio
        property: minio.values
