---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bge-reranker-v2-m3-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bge-reranker-v2-m3
  template:
    metadata:
      labels:
        app: bge-reranker-v2-m3
    spec:
      containers:
        - name: bge-reranker-v2-m3
          image: vllm/vllm-openai:v0.8.5
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve BAAI/bge-reranker-v2-m3 --task score --trust-remote-code --max_num_batched_tokens 8192 --max_model_len 8192"
          ]
          envFrom:
            - secretRef:
                name: huggingface-secrets
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "4"
              memory: 8G
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 4G
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - ai-lab-1
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: bge-reranker-v2-m3-pvc
        # vLLM needs to access the host's shared memory for tensor parallel inference.
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: bge-reranker-v2-m3-service
spec:
  type: ClusterIP
  selector:
    app: bge-reranker-v2-m3
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
