apiVersion: batch/v1
kind: CronJob
metadata:
  name: insect-project-comments-report
spec:
  schedule: "0 13 * * 1" # Run at 9:00 AM Eastern Time (UTC-4) on Mondays only
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: type
                        operator: In
                        values:
                          - app-worker
          containers:
            - name: insect-project-comments-report
              image: ghcr.io/ai-cfia/insect-project:4f976e572223d46cd0b5c7cb0991a288341204a7
              args: ["comments"]
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: insect-project-common-secrets
                - secretRef:
                    name: insect-project-comments-secrets
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
                limits:
                  memory: "2Gi"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
          restartPolicy: Never
