apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insect-project-common-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: insect-project-common-secrets
  dataFrom:
    - extract:
        key: secrets/insect-project/common
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insect-project-observations-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: insect-project-observations-secrets
  dataFrom:
    - extract:
        key: secrets/insect-project/observations
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insect-project-comments-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: insect-project-comments-secrets
  dataFrom:
    - extract:
        key: secrets/insect-project/comments
