apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  sources:
    - chart: traefik
      helm:
        releaseName: traefik
        valueFiles:
          - $values/networking/traefik/helm/values.yaml
      repoURL: https://traefik.github.io/charts
      targetRevision: 36.0.0
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
