apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      # caProvider:
      #   type: "Secret"
      #   namespace: "vault"
      #   name: "vault-ca-tls"
      #   key: "ca.crt"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          namespace: "vault"
          key: "root_token"

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-devsecops-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "devsecops"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          namespace: "vault"
          key: "root_token"
---
# This secret won't be tracked by argocd
# TODO: Change the tokenSecretRef to OIDC
###
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-token
#   namespace: vault
# data:
#   token: cm9vdA== # "root"
