---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  sources:
    - chart: minio
      helm:
        valueFiles:
          - $values/storage/minio/helm/values.yaml
      repoURL: https://charts.min.io/
      targetRevision: 5.4.0
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: kubernetes/aks/system/minio/base
      targetRevision: HEAD
