apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: louis-gateway
  namespace: louis
spec:
  addresses:
    - type: IPAddress
      value: 10.140.79.6
  gatewayClassName: cilium
  listeners:
    - name: https-louis
      hostname: louis.inspection.alpha.canada.ca
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: openwebui-tls
            kind: Secret
    - name: all-http
      port: 80
      protocol: HTTP
      allowedRoutes:
        kinds:
        - kind: HTTPRoute
        namespaces:
          from: All
