---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - litellm/deployment.yaml
  - litellm/configmap.yaml
  - litellm/secrets.yaml
  - litellm/ingress.yaml
  - ollama/deployment.yaml
  - openwebui/deployment.yaml
  - openwebui/ingress.yaml
  - openwebui/pvcs.yaml
  - openwebui/secrets.yaml
