apiVersion: v1
kind: ConfigMap
metadata:
  name: openwebui-configenv
data:
  ENV: "dev"
  WEBUI_NAME: "AI Lab AMI"
  ADMIN_EMAIL: "thomas.cardin@inspection.gc.ca"
  DEFAULT_USER_ROLE: "user"
  ENABLE_SIGNUP: "true"
  ENABLE_LOGIN_FORM: "true"
  ENABLE_ADMIN_CHAT_ACCESS: "false"
  VECTOR_DB: "pgvector"
  GLOBAL_LOG_LEVEL: "INFO"
  # CHROMA_HTTP_HOST: "chromadb-service.louis.svc.cluster.local"
  # CHROMA_HTTP_PORT: "8000"
