apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/ai-cfia/open-webui:git-eb5c47f
          resources:
            requests:
              cpu: 2
              memory: 8G
            limits:
              cpu: 8
              memory: 32Gi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: openwebui-configenv
            - secretRef:
                name: openwebui-secrets
            - secretRef:
                name: openwebui-connection-string
          env:
            - name: ENABLE_OTEL
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.monitoring.svc.cluster.local:4317"
          tty: true
          volumeMounts:
            - name: openwebui-volume
              mountPath: /app/backend/data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      volumes:
        - name: openwebui-volume
          persistentVolumeClaim:
            claimName: openwebui-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
