apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: open-webui-pvc
spec:
  storageClassName: ceph-hot-block
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
