---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
  dataFrom:
    - extract:
        key: secrets/louis/openwebui

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-connection-string
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: openwebui-connection-string
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username | toString }}:{{ .password | toString }}@{{ .base_url | toString }}{{ .app_db | toString }}"
        PGVECTOR_DB_URL: "postgresql://{{ .superuser | toString }}:{{ .superpass | toString | urlquery }}@{{ .base_url | toString }}{{ .vector_db | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: devsecops/cloudnativepg/openwebui-dev-user
        property: username
    - secretKey: password
      remoteRef:
        key: devsecops/cloudnativepg/openwebui-dev-user
        property: password
    - secretKey: base_url
      remoteRef:
        key: devsecops/cloudnativepg/openwebui-dev-user
        property: base_url
    - secretKey: app_db
      remoteRef:
        key: devsecops/cloudnativepg/openwebui-dev-user
        property: app_db
    - secretKey: vector_db
      remoteRef:
        key: devsecops/cloudnativepg/openwebui-dev-user
        property: vector_db
    - secretKey: superuser
      remoteRef:
        key: devsecops/cloudnativepg/acia-cfia-dev-cluster
        property: username
    - secretKey: superpass
      remoteRef:
        key: devsecops/cloudnativepg/acia-cfia-dev-cluster
        property: password
