---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-secrets
  namespace: louis
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: openwebui-secrets
  dataFrom:
    - extract:
        key: secrets/louis/openwebui
