apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fertiscan-backend-frontend-ingress
  annotations:
    # lbipam.cilium.io/ips: 10.140.79.21  # TODO
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: fertiscan-backend-svc
                port:
                  number: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fertiscan-frontend-ingress
  annotations:
    # lbipam.cilium.io/ips: 10.140.79.22  # TODO
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fertiscan-frontend-svc
                port:
                  number: 3000
          - path: /swagger(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: fertiscan-backend-svc
                port:
                  number: 5000
