apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fertiscan-backend-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: fertiscan-backend-secrets
  dataFrom:
    - extract:
        key: secrets/fertiscan/backend
        property: fertiscan-backend.values

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: fertiscan-backend-preview-secrets
#   namespace: fertiscan-preview
# data:
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
