apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-hot-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: rook-ceph-hot-cluster
    server: https://kubernetes.default.svc
  sources:
    - chart: rook-ceph-cluster
      helm:
        releaseName: rook-ceph-hot-cluster
        valueFiles:
          - $values/storage/rook-ceph/clusters/rook-ceph-hot-cluster/helm/values.yaml
      repoURL: https://charts.rook.io/release
      targetRevision: v1.17.7
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: storage/rook-ceph/clusters/rook-ceph-hot-cluster/base/
      targetRevision: HEAD
