apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gpt-researcher-tls
spec:
  secretName: gpt-researcher-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - ACIA CFIA AI Lab
  commonName: gptr.inspection.alpha.canada.ca
  dnsNames:
    - gptr-b.inspection.alpha.canada.ca
    - gptr.inspection.alpha.canada.ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
