apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-researcher-backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gpt-researcher-backend
  template:
    metadata:
      labels:
        app: gpt-researcher-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: gpt-researcher-backend
          image: ghcr.io/ai-cfia/gpt-researcher@sha256:48565f89d21795f3e101e2ca30e8707d6868d2ccb87ac51afb81b8068afc74e8 # latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gpt-researcher-secrets
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: docs-pvc
              mountPath: /usr/src/app/my-docs
      volumes:
        - name: docs-pvc
          persistentVolumeClaim:
            claimName: gptresearcher-my-docs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gptresearcher-my-docs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-hot-block
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-researcher-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gpt-researcher-frontend
  template:
    metadata:
      labels:
        app: gpt-researcher-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      containers:
        - name: gpt-researcher-frontend
          image: ghcr.io/ai-cfia/gpt-researcher-frontend-prod@sha256:5fb670d7d90070a7e1ffac38b9a84f7cbc59058361d822a0cf784005a26dce79
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-researcher-frontend-svc
spec:
  clusterIP: None
  selector:
    app: gpt-researcher-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-researcher-backend-svc
spec:
  clusterIP: None
  selector:
    app: gpt-researcher-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-researcher-ingress
  annotations:
    lbipam.cilium.io/ips: 10.140.79.11
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - gptr.inspection.alpha.canada.ca
    secretName: gpt-researcher-tls
  rules:
    - host: gptr.inspection.alpha.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpt-researcher-frontend-svc
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-researcher-backend-ingress
  annotations:
    lbipam.cilium.io/ips: 10.140.79.18
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - gptr-b.inspection.alpha.canada.ca
    secretName: gpt-researcher-tls
  rules:
    - host: gptr-b.inspection.alpha.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpt-researcher-backend-svc
                port:
                  number: 8000
