apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-researcher-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gpt-researcher-frontend
  template:
    metadata:
      labels:
        app: gpt-researcher-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      containers:
        - name: gpt-researcher-frontend
          image: ghcr.io/ai-cfia/gpt-researcher-frontend-prod@sha256:436eb98d098f533716469b2ed4ed8f605f6da914b45f6a444c3fb4d270c3d068
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-researcher-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: gpt-researcher-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
