apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gpt-researcher-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gpt-researcher-secrets
  dataFrom:
    - extract:
        key: secrets/gpt-researcher
