# -- Number of replicas
replicaCount: 1

# -- The number of old ReplicaSets to retain
revisionHistoryLimit: 3

service:
  # -- Kubernetes service type
  type: ClusterIP
  # -- Kubernetes port where service is exposed
  port: 9003

# -- Toleration labels for pod assignment
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"

# -- Affinity settings for pod assignment
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - app-worker

prometheus:
  # -- The dashboards that will be displayed in the Argo CD UI
  # @default -- see [values.yaml](./values.yaml)
  dashboards: |
    {
      "groupKind": "pod",
      "tabs": ["Golden Signal"],
      "rows": [
        {
          "name": "pod",
          "title": "Pods",
          "tab": "Golden Signal",
          "graphs": [
            {
              "name": "pod_cpu_line",
              "title": "CPU",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_cpu_pie",
              "title": "CPU Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_line",
              "title": "Memory",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_pie",
              "title": "Mem Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            }
          ]
        },
        {
          "name": "container",
          "title": "Containers",
          "tab": "Golden Signal",
          "graphs": [
            {
              "name": "container_cpu_line",
              "title": "CPU",
              "description": "",
              "graphType": "line",
              "metricName": "container",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (container)"
            },
            {
              "name": "container_cpu_pie",
              "title": "CPU Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "container",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\",container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (container)"
            },
            {
              "name": "container_memory_line",
              "title": "Memory",
              "description": "",
              "graphType": "line",
              "metricName": "container",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (container)"
            },
            {
              "name": "container_memory_pie",
              "title": "Mem Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "container",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (container)"
            }
          ]
        }
      ]
    },
    {
      "groupKind": "deployment",
      "tabs": ["Golden Signal"],
      "rows": [
          {
            "name": "httplatency",
            "title": "HTTP Latency",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_200_latency",
                "title": "Latency",
                "description": "",
                "graphType": "line",
                "metricName": "pod_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_sum {namespace=\"{{.namespace}}\", status=\"200\"} [1m])) by (pod_template_hash)"
              }
            ]
          },
          {
            "name": "httperrortate",
            "title": "HTTP Error Rate",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_error_rate_500",
                "title": "HTTP Error 500",
                "description": "",
                "graphType": "line",
                "metricName": "pod_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\", status=\"500\"} [1m])) by (pod_template_hash)"
              },
              {
                "name": "http_error_rate_400",
                "title": "HTTP Error 400",
                "description": "",
                "graphType": "line",
                "metricName": "pod_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\", status=\"404\"} [1m])) by (pod_template_hash)"
              }
            ]
          },
          {
            "name": "httptraffic",
            "title": "HTTP Traffic",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_traffic",
                "title": "Traffic",
                "description": "",
                "graphType": "line",
                "metricName": "pod_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\"} [1m])) by (pod_template_hash)"
              }
            ]
          },
        {
          "name": "pod",
          "title": "Pods",
          "tab": "Golden Signal",
          "graphs": [
            {
              "name": "pod_cpu_line",
              "title": "CPU",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_cpu_pie",
              "title": "CPU Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_line",
              "title": "Memory",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_pie",
              "title": "Mem Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            }
          ]
        }
      ]
    },
    {
      "groupKind": "rollout",
      "tabs": ["Golden Signal"],
      "rows": [
          {
            "name": "httplatency",
            "title": "HTTP Latency",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_200_latency",
                "title": "Latency",
                "description": "",
                "graphType": "line",
                "metricName": "rollout_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_sum {namespace=\"{{.namespace}}\", status=\"200\"} [1m])) by (rollout_template_hash)"
              }
            ]
          },
          {
            "name": "httperrortate",
            "title": "HTTP Error Rate",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_error_rate_500",
                "title": "HTTP Error 500",
                "description": "",
                "graphType": "line",
                "metricName": "rollout_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\", status=\"500\"} [1m])) by (rollout_template_hash)"
              },
              {
                "name": "http_error_rate_400",
                "title": "HTTP Error 400",
                "description": "",
                "graphType": "line",
                "metricName": "rollout_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\", status=\"404\"} [1m])) by (rollout_template_hash)"
              }
            ]
          },
          {
            "name": "httptraffic",
            "title": "HTTP Traffic",
            "tab": "Golden Signal",
            "graphs": [
              {
                "name": "http_traffic",
                "title": "Traffic",
                "description": "",
                "graphType": "line",
                "metricName": "rollout_template_hash",
                "queryExpression": "sum(rate(http_server_requests_seconds_count {namespace=\"{{.namespace}}\"} [1m])) by (rollout_template_hash)"
              }
            ]
          },
        {
          "name": "pod",
          "title": "Pods",
          "tab": "Golden Signal",
          "graphs": [
            {
              "name": "pod_cpu_line",
              "title": "CPU",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\", container!=\"POD\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_cpu_pie",
              "title": "CPU Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_line",
              "title": "Memory",
              "description": "",
              "graphType": "line",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            },
            {
              "name": "pod_memory_pie",
              "title": "Mem Avg",
              "description": "",
              "graphType": "pie",
              "metricName": "pod",
              "queryExpression": "sum(rate(container_memory_usage_bytes{pod=~\"{{.name}}\", container!=\"POD\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (pod)"
            }
          ]
        }
      ]
    }
  # -- The namespace where Prometheus is running
  namespace: monitoring
  # -- The port on which the Prometheus service is listening for traffic
  port: 8080
  # -- The name of the Prometheus service
  service: lgtm-distributed-mimir-query-frontend
