apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - chart: keycloak
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 25.2.0
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/security/keycloak/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: security/keycloak/base
      targetRevision: HEAD
