apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: acia-cfia-dev-cluster-backup
spec:
  schedule: "0 0 * * 5"  # Friday midnight (UTC)
  backupOwnerReference: self
  cluster:
    name: acia-cfia-dev-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
