apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: acia-cfia-dev-cluster-store
  namespace: cloudnativepg
spec:
  configuration:
    destinationPath: s3://acia-cfia-dev-cluster-backup/
    endpointURL: http://minio-svc.minio:9000
    s3Credentials:
      accessKeyId:
        name: minio-secret
        key: rootUser
      secretAccessKey:
        name: minio-secret
        key: rootPassword
    wal:
      compression: gzip
    data:
      additionalCommandArgs:
        - "--min-chunk-size=5MB"
        - "--read-timeout=60"
        - "-vv"
  retentionPolicy: "10d"
