apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: acia-cfia-dev-cluster
spec:
  description: "ACIA-CFIA dev cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 3
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all 10.140.79.0/24 md5

  storage:
    storageClass: ceph-block
    size: 70Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - worker
    enablePodAntiAffinity: true
