apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: acia-cfia-dev-cluster
spec:
  description: "ACIA-CFIA dev cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.3
  instances: 2
  primaryUpdateStrategy: unsupervised

  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 md5

  managed:
    roles:
      - name: fertiscan
        ensure: present
        comment: "Owner of fertiscan databases"
        login: true
        createdb: true
        createrole: false
        inherit: true
        replication: false
        bypassrls: false
        connectionLimit: 10
        passwordSecret:
          name: fertiscan-user-creds

  storage:
    storageClass: ceph-block
    size: 70Gi

  enableSuperuserAccess: true
  superuserSecret:
    name: acia-cfia-dev-cluster-creds

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - worker
    enablePodAntiAffinity: true
