apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acia-cfia-dev-cluster-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: acia-cfia-dev-cluster-creds
    type: kubernetes.io/basic-auth
    template:
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/acia-cfia-dev-cluster
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/acia-cfia-dev-cluster
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fertiscan-preview-user-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: fertiscan-preview-user-creds
    type: kubernetes.io/basic-auth
    template:
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/fertiscan-preview-user
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/fertiscan-preview-user
        property: password