apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-idontexist-store
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
  - secretKey: vault-eso-test
    remoteRef:
      key: secrets/howard-on-prem/test
      property: test

  # # metadataPolicy to fetch all the labels in JSON format
  # - secretKey: tags
  #   remoteRef:
  #     metadataPolicy: Fetch 
  #     key: foo

  # # metadataPolicy to fetch a specific label (dev) from the source secret
  # - secretKey: developer
  #   remoteRef:
  #     metadataPolicy: Fetch 
  #     key: foo
  #     property: dev

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: demo-secret
# data:
#   vault-eso-test: czNjcjN0
