apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: finesse-frontend-tls
  namespace: finesse
spec:
  secretName: finesse-frontend-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - ACIA CFIA AI Lab
  commonName: finesse.inspection.alpha.canada.ca
  dnsNames:
    - finesse.inspection.alpha.canada.ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: finesse-backend-tls
  namespace: finesse
spec:
  secretName: finesse-backend-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - ACIA CFIA AI Lab
  commonName: finesse-backend.inspection.alpha.canada.ca
  dnsNames:
    - finesse-backend.inspection.alpha.canada.ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
