# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: finesse-backend-ingress
#   annotations:
#     lbipam.cilium.io/ips: 10.140.79.27
#     ingress.cilium.io/loadbalancer-mode: dedicated
# spec:
#   ingressClassName: cilium
#   rules:
#     - http:
#         paths:
#           - path: /api(/|$)(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: finesse-backend-svc
#                 port:
#                   number: 5000

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: finesse-frontend-ingress
#   annotations:
#     lbipam.cilium.io/ips: 10.140.79.28
#     ingress.cilium.io/loadbalancer-mode: dedicated
# spec:
#   ingressClassName: cilium
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: finesse-frontend-svc
#                 port:
#                   number: 3000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finesse-ingress
  annotations:
    lbipam.cilium.io/ips: 10.140.79.28  # Une seule IP
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: finesse-backend-svc
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finesse-frontend-svc
                port:
                  number: 3000
