apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: finesse-backend-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: finesse-backend-secrets
  dataFrom:
    - extract:
        key: secrets/finesse/backend
        property: finesse-backend.values

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: finesse-backend-secrets
#   namespace: finesse
# data:
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
