apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jsantos-webtop-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: jsantos-webtop-secrets
  dataFrom:
    - extract:
        key: secrets/webtop/jsantos
# stringData:
#   PUID: <PUID>
#   PGID: <PGID>
#   TZ: <TZ>
#   TITLE: <TITLE>
#   CUSTOM_USER: <CUSTOM_USER>
#   PASSWORD: <PASSWORD>
