apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-a45fb23a-fd99-4797-94da-ac0077141f89-webtop
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 14Ti
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user
      namespace: rook-ceph-cold-cluster
    volumeAttributes:
      clusterID: rook-ceph-cold-cluster
      fsName: ceph-cold-filesystem
      storage.kubernetes.io/csiProvisionerIdentity: 1741357536395-2839-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-532e7bfd-ff0b-4dd7-8dff-0dab9e75f17b
      subvolumePath: /volumes/csi/csi-vol-532e7bfd-ff0b-4dd7-8dff-0dab9e75f17b/c1dc717f-7d1f-41e9-afbc-7aa409db135d
      staticVolume: "true"
      rootPath: /volumes/csi/csi-vol-532e7bfd-ff0b-4dd7-8dff-0dab9e75f17b/c1dc717f-7d1f-41e9-afbc-7aa409db135d
    volumeHandle: 0001-0016-rook-ceph-cold-cluster-0000000000000001-532e7bfd-ff0b-4dd7-8dff-0dab9e75f17b-webtop
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ceph-cold-filesystem
  volumeMode: Filesystem
