apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcardin-webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcardin-webtop
  template:
    metadata:
      labels:
        app: tcardin-webtop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - ai-lab-2
      containers:
      - name: webtop
        image: lscr.io/linuxserver/webtop:ubuntu-xfce
        ports:
        - containerPort: 3000
        env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        - name: DOCKER_TLS_CERTDIR
          value: ""
        envFrom:
        - secretRef:
            name: tcardin-webtop-secrets
        volumeMounts:
        - name: config
          mountPath: /config
      - name: docker-dind
        image: docker:dind
        securityContext:
          privileged: true
        ports:
        - containerPort: 2375
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        args:
        - "--host=tcp://0.0.0.0:2375"
        - "--tls=false"
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tcardin-webtop-config-pvc
      - name: docker-graph-storage
        emptyDir: {}
      - name: ailab-shared
        persistentVolumeClaim:
          claimName: tcardin-webtop-shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tcardin-webtop-service
spec:
  type: ClusterIP
  selector:
    app: tcardin-webtop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcardin-webtop-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ceph-hot-filesystem
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcardin-webtop-shared-pvc
  namespace: webtop
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14Ti
  volumeName: pvc-a45fb23a-fd99-4797-94da-ac0077141f89-webtop
  storageClassName: ceph-cold-filesystem
  volumeMode: Filesystem
