apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nachet-dev-backend-ingress
  namespace: nachet-dev
  annotations:
    lbipam.cilium.io/ips: 10.140.79.16
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - nachet-backend.inspection.alpha.canada.ca
    secretName: nachet-backend-tls
  rules:
    - host: nachet-backend.inspection.alpha.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nachet-backend-svc
                port:
                  number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nachet-dev-frontend-ingress
  namespace: nachet-dev
  annotations:
    lbipam.cilium.io/ips: 10.140.79.17
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - nachet.inspection.alpha.canada.ca
    secretName: nachet-frontend-tls
  rules:
    - host: nachet.inspection.alpha.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nachet-frontend-svc
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nachet-dev-azurite-ingress
  namespace: nachet-dev
  annotations:
    lbipam.cilium.io/ips: 10.140.79.15
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  # tls:
  # - hosts:
  #   - nachet-blob.inspection.alpha.canada.ca
  #   secretName: nachet-blob-tls
  rules:
    # - host: nachet-blob.inspection.alpha.canada.ca
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nachet-azurite-svc
                port:
                  number: 10000
