apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachet-frontend
  namespace: nachet-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nachet-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nachet-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nachet-frontend
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ai-lab-2
      containers:
        - name: nachet-frontend
          image: ghcr.io/ai-cfia/nachet-frontend:203-update-container-deployment
          imagePullPolicy: Always
          # command: ["/bin/sh", "-c"]
          # args: [serve -s build]
          envFrom:
            - secretRef:
                name: nachet-frontend-secrets
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: node
              mountPath: /home/node
            - name: node_modules
              mountPath: /nachet-frontend/node_modules
      volumes:
        - name: node
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
        - name: node_modules
          emptyDir:
            medium: Memory
            sizeLimit: 400Mi

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nachet-frontend-pdb
  namespace: nachet-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nachet-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: nachet-frontend-svc
  namespace: nachet-dev
spec:
  clusterIP: None
  selector:
    app: nachet-frontend
  ports:
    - protocol: TCP
      port: 3000
