---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-frontend-secrets
  namespace: nachet-dev
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-frontend-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/azure

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-backend-secrets
  namespace: nachet-dev
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-backend-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/azure

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-db-connection-string
  namespace: nachet-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-db-connection-string
    template:
      engineVersion: v2
      data:
        NACHET_DB_URL: "postgresql://{{ .username | toString }}:{{ .password | toString }}@{{ .base_url | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_DB_USER
    - secretKey: password
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_DB_PASSWORD
    - secretKey: base_url
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_DB_BASE_URL

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-storage-url
  namespace: nachet-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-storage-url
    template:
      engineVersion: v2
      data:
        NACHET_STORAGE_URL: "DefaultEndpointsProtocol=http;AccountName={{ .account_name | toString }};AccountKey={{ .account_key | toString }};"
    creationPolicy: Owner
  data:
    - secretKey: account_name
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_BLOB_ACCOUNT
    - secretKey: account_key
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_BLOB_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nachet-storage-connection-string
  namespace: nachet-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-storage-connection-string
    template:
      engineVersion: v2
      data:
        NACHET_AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName={{ .account_name | toString }};AccountKey={{ .account_key | toString }};BlobEndpoint={{ .blob_endpoint | toString }};"
    creationPolicy: Owner
  data:
    - secretKey: account_name
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_BLOB_ACCOUNT
    - secretKey: account_key
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_BLOB_KEY
    - secretKey: blob_endpoint
      remoteRef:
        key: secrets/nachet/azure
        property: NACHET_BLOB_ENDPOINT
