---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-frontend-secrets
  namespace: nachet-dev
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-frontend-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/azure

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-backend-secrets
  namespace: nachet-dev
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-backend-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/azure
