apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-azure-secrets
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-azure-secrets
  dataFrom:
    - extract:
        key: secrets/nachet/azure
        property: entries


