apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rook-h-route
spec:
  parentRefs:
    - name: storage-gateway
      sectionName: https-rook-h
      namespace: rook-ceph
  hostnames:
    - rook-h.inspection.alpha.canada.ca
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: rook-ceph-mgr-dashboard
          port: 8443
