---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - labelstudio/pvcs.yaml
  - labelstudio/secrets.yaml
  - labelstudio/labelstudio.yaml
  - labelstudio/certificates.yaml
  - fiftyone/fiftyone.yaml
  - fiftyone/s3-secrets.yaml
  - httproute.yaml
