apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ragflow-infinity
  labels:
    app.kubernetes.io/component: infinity
spec:
  storageClassName: ceph-cold-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragflow-infinity
  labels:
    app.kubernetes.io/component: infinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: infinity
  template:
    metadata:
      labels:
        app.kubernetes.io/component: infinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - ai-worker
      containers:
      - name: infinity
        image: infiniflow/infinity:v0.5.0
        envFrom:
          - secretRef:
              name: ragflow-env-config
        ports:
          - containerPort: 23817
            name: thrift
          - containerPort: 23820
            name: http
          - containerPort: 5432
            name: psql
        volumeMounts:
          - mountPath: /var/infinity
            name: infinity-data
        securityContext:
          capabilities:
            add:
              - "NET_BIND_SERVICE"
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /admin/node/current
            port: 23820
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
      volumes:
        - name: infinity-data
          persistentVolumeClaim:
            claimName: ragflow-infinity
---
apiVersion: v1
kind: Service
metadata:
  name: ragflow-infinity
  labels:
    app.kubernetes.io/component: infinity
spec:
  selector:
      app.kubernetes.io/component: infinity
  ports:
    - protocol: TCP
      port: 23817
      targetPort: thrift
      name: thrift
    - protocol: TCP
      port: 23820
      targetPort: http
      name: http
    - protocol: TCP
      port: 5432
      targetPort: psql
      name: psql
  type: ClusterIP
