apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-ai-lab-1
  namespace: nvidia
data:
   ai-lab-1: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 8
