apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/networking/nginx/helm/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.13.3
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
