apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: docling
  template:
    metadata:
      labels:
        app: docling
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: docling
          image: ghcr.io/docling-project/docling-serve-cpu
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: DOCLING_SERVE_ENABLE_UI
              value: "true"
            - name: DOCLING_SERVE_ARTIFACTS_PATH
              value: "/app/artifacts"
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: docling-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docling-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-hot-block
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: docling-service
spec:
  selector:
    app: docling
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
