apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  sources:
    - chart: harbor
      helm:
        releaseName: harbor
        valueFiles:
          - $values/kubernetes/apps/harbor/helm/values.yaml
      repoURL: https://helm.goharbor.io
      targetRevision: 1.15.1
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: kubernetes/apps/harbor/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
