apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: thomas.cardin@inspection.gc.ca
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          azureDNS:
            hostedZoneName: inspection.alpha.canada.ca
            resourceGroupName: rg-acia-cfia-howard
            subscriptionID: b72bb8e9-f530-4d72-bc2f-5ad441b65787            
            environment: AzurePublicCloud
            managedIdentity:
              clientID: a2ed7289-c916-4075-86ff-f67602be7a9b
