apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-service-tls
  namespace: default  # Change this to the namespace of your service
spec:
  secretName: example-service-tls
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days
  subject:
    organizations:
      - Your Organization
  commonName: example-service.local
  dnsNames:
    - example-service.local
    - example-service
    - example-service.default.svc.cluster.local
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io 