apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nachet-service-tls
  namespace: default  # Change this to the namespace of your service
spec:
  secretName: nachet-service-tls
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days
  subject:
    organizations:
      - ACIA CFIA AI Lab
  commonName: nachet-on-prem.inspection.alpha.canada.ca
  dnsNames:
    - nachet-on-prem.inspection.alpha.canada.ca
    - nachet-on-prem
    - nachet-dev.default.svc.cluster.local
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io 