apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azuredns-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: azuredns-config
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/azure-sp
