apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuredns-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: azuredns-config
  dataFrom:
    - extract:
        key: devsecops/azure-sp
