apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-dev-cluster-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-dev-cluster-creds
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-dev-cluster
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-dev-cluster
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nachet-dev-user-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nachet-dev-user-creds
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-dev-user
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/howard-on-prem/cloudnativepg/nachet-dev-user
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret-nachet-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-secret-nachet-dev
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/minio
        property: minio.values
