apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-state-metrics
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - chart: kube-state-metrics
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.32.0
      helm:
        releaseName: kube-state-metrics
        valueFiles:
          - $values/monitoring/k8s-state-metrics/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
