---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ragflow-redis
  labels:
    app.kubernetes.io/component: redis
spec:
  storageClassName: ceph-hot-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragflow-redis
  labels:
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      containers:
      - name: redis
        image: valkey/valkey:8
        command:
          - "sh"
          - "-c"
          - "exec redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru"
        envFrom:
          - secretRef:
              name: ragflow-env-config
        ports:
          - containerPort: 6379
            name: redis
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: ragflow-redis
---
apiVersion: v1
kind: Service
metadata:
  name: ragflow-redis
  labels:
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis
  type: ClusterIP
