apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.29.1
      helm:
        releaseName: vault
        valueFiles:
          - $values/security/vault/helm/vault.yaml
    - chart: vault-autounseal
      repoURL: https://pytoshka.github.io/vault-autounseal
      targetRevision: 0.5.3
      helm:
        releaseName: vault-autounseal
        valueFiles:
          - $values/security/vault/helm/autounseal.yaml
    # - repoURL: https://github.com/ai-cfia/howard-on-prem.git
    #   targetRevision: HEAD
    #   ref: vault
    # - repoURL: https://github.com/ai-cfia/howard-on-prem.git
    #   targetRevision: HEAD
    #   ref: autounseal
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: security/vault/base
      targetRevision: HEAD
