# waiting for BackendTLSPolicy: https://github.com/cilium/cilium/issues/31352
# more info here: https://gateway-api.sigs.k8s.io/api-types/backendtlspolicy/?h=backendtlspolicy
# replace procotol to HTTPS: https://gateway-api.sigs.k8s.io/guides/tls/

# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: Gateway
# metadata:
#   name: vault-gateway
# spec:
#   addresses:
#     - type: IPAddress
#       value: 10.140.79.12
#   gatewayClassName: cilium
#   listeners:
#     - name: https-vault
#       hostname: vault.inspection.alpha.canada.ca
#       port: 443
#       protocol: HTTPS
#       tls:
#         mode: Terminate
#         certificateRefs:
#           - kind: Secret
#             name: vault-tls

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: vault-gateway
spec:
  addresses:
    - type: IPAddress
      value: 10.140.79.12
  gatewayClassName: cilium
  listeners:
    - name: https-vault
      hostname: vault.inspection.alpha.canada.ca
      port: 443
      protocol: TLS
      tls:
        mode: Passthrough
        certificateRefs:
          - kind: Secret
            name: vault-tls
