apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-internal-ingress
  namespace: vault
  labels:
    ingress: cilium
    app: vault
  annotations:
    lbipam.cilium.io/ips: 10.140.79.12
    ingress.cilium.io/loadbalancer-mode: dedicated
spec:
  ingressClassName: cilium
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vault-ui
              port:
                number: 8200

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: vault-external-ingress
#   namespace: vault
#   labels:
#     ingress: cilium
#     app: vault
#   annotations:
#     ingress.cilium.io/force-https: enabled
#     cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   ingressClassName: cilium
#   rules:
#     - http:
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: vault-ui
#               port:
#                 name: https
