apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  sources:
    - chart: mlflow
      repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 1.7.3
      helm:
        releaseName: mlflow
        valueFiles:
          - $values/mlops/mlflow/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: mlops/mlflow/base
      targetRevision: HEAD
