apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acia-cfia-dev-cluster/cluster.yaml
  - acia-cfia-dev-cluster/secrets.yaml
  - acia-cfia-dev-cluster/backup.yaml
  - acia-cfia-dev-cluster/barman-objectstore.yaml
  
  - database/fertiscan-preview.yaml
  - database/nachet-dev.yaml
  - database/finesse.yaml
  - database/finesse-internal.yaml
  - database/litellm.yaml
  - database/openwebui.yaml
  - database/openwebui-vector.yaml
  - database/keycloak-database.yaml
  - database/nachet-prod.yaml
  - database/memos.yaml
  - database/mlflow.yaml
  - database/labelstudio.yaml
  - database/harbor.yaml

  - acia-cfia-prod-cluster/cluster.yaml
  - acia-cfia-prod-cluster/secrets.yaml
  - acia-cfia-prod-cluster/backup.yaml
  - acia-cfia-prod-cluster/barman-objectstore.yaml

  - barman-cloud/deployment.yaml
