apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - acia-cfia-dev-cluster/cluster.yaml
 - acia-cfia-dev-cluster/secrets.yaml
 - acia-cfia-dev-cluster/backup.yaml

 - database/fertiscan-preview.yaml

 - nachet-dev-cluster/cluster.yaml
 - nachet-dev-cluster/secrets.yaml
 - nachet-dev-cluster/backup.yaml

 - database/nachet-dev.yaml

 - nachet-prod-cluster/cluster.yaml
 - nachet-prod-cluster/secrets.yaml
 - nachet-prod-cluster/backup.yaml

 - database/nachet-prod.yaml
