apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - acia-cfia-dev-cluster/cluster.yaml
 - acia-cfia-dev-cluster/snapshot.yaml
 - acia-cfia-dev-cluster/credentials.yaml

 - acia-cfia-prod-cluster/cluster.yaml
 - acia-cfia-prod-cluster/snapshot.yaml
 - acia-cfia-prod-cluster/credentials.yaml


