apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: finesse-internal-backend-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: finesse-internal-backend-secrets
  dataFrom:
    - extract:
        key: secrets/finesse-internal/backend
        property: finesse-internal-backend.values

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: finesse-internal-backend-secrets
#   namespace: finesse-internal
# data:
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
#   .....: ....
