---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ailab-shared-gateway
spec:
  addresses:
    - type: IPAddress
      value: 10.140.79.7
  gatewayClassName: traefik
  listeners:
    - name: tcp-pytorchdev
      port: 80
      protocol: TCP
