kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ailab-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14Ti
  storageClassName: ceph-cold-filesystem
  volumeMode: Filesystem
