---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: pytorchdev-tcp
spec:
  parentRefs:
    - name: ailab-shared-gateway
      sectionName: tcp-pytorchdev
      kind: Gateway
  rules:
    - forwardTo:
        - service:
            name: pytorchdevssh-svc
            port: 22
            namespace: ailab-shared
    #  - backendRefs:
    #     - name: pytorchdevssh-svc
    #       namespace: ailab-shared
    #       port: 22
