---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: pytorchdev-tcp
spec:
  parentRefs:
    - name: ailab-shared-gateway
      sectionName: tcp-pytorchdev
      kind: Gateway

  rules:
     - backendRefs:
        - name: pytorchdev-svc
          namespace: ailab-shared
          port: 22
