apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triton
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: triton
  sources:
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: mlops/triton/base
      targetRevision: HEAD
