apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-es-config
data:
  node.name: "es01"
  bootstrap.memory_lock: "false"
  discovery.type: "single-node"
  xpack.security.enabled: "true"
  xpack.security.http.ssl.enabled: "false"
  xpack.security.transport.ssl.enabled: "false"
