apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-bridge-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mcp-bridge
  template:
    metadata:
      labels:
        app: mcp-bridge
    spec:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mcp-bridge
          image: ghcr.io/ai-cfia/louis/mcp-bridge:louis-3e891a1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mcp-bridge-secrets
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
