apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-bridge-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mcp-bridge
  template:
    metadata:
      labels:
        app: mcp-bridge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app-worker
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mcp-bridge
          image: ghcr.io/secretiveshell/mcp-bridge/mcp-bridge:0.5.1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mcp-bridge-secrets
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: cache-volume
              mountPath: /.cache/
              
      volumes:
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-bridge-service
spec:
  selector:
    app: mcp-bridge
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
