---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: argo-workflows-sso
  data:
    - secretKey: client-id
      remoteRef:
        key: devsecops/keycloak
        property: argo-workflows-client-id
    - secretKey: client-secret
      remoteRef:
        key: devsecops/keycloak
        property: argo-workflows-client-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-admin.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-admin
type: kubernetes.io/service-account-token
