apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
spec:
  storageClassName: ceph-cold-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
