name: Terraform staging plan and apply

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  deploy:
    runs-on: on-prem-gh-runners

    env:
      # Azure authentication
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinIO client
        run: |
          curl -sO https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/mc

      - name: Configure mc (MinIO client)
        run: |
          mc alias set minio https://minio.inspection.alpha.canada.ca "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"

      - name: ls
        run: |
          ls
      - name: Download staging.tfvars from MinIO
        run: |
          mc cp minio/terraform-staging-vars/staging.tfvars ./terraform/staging/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform/staging
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file=staging.tfvars

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -var-file=staging.tfvars -auto-approve
