name: Howard on prem integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  pr-labelling:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-pr-labelling.yml@main
    secrets: inherit

  check-commit-author:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-check-author-email.yml@main
    secrets: inherit
