apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia
  sources:
    - chart: gpu-operator
      repoURL: https://helm.ngc.nvidia.com/nvidia
      targetRevision: v25.3.1
      helm:
        releaseName: gpu-operator
        valueFiles:
          - $values/mlops/nvidia/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: mlops/nvidia/base
      targetRevision: HEAD
