apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-secrets
  dataFrom:
    - extract:
        key: secrets/howard-on-prem/pgadmin
        property: pgadmin.values