apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: pgadmin-secrets
  dataFrom:
    - extract:
        key: devsecops/pgadmin
        property: pgadmin.values
