apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: argocd-config
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: oidc.keycloak.clientSecret
      remoteRef:
        key: devsecops/keycloak
        property: argocd-client-secret
    - secretKey: github-privateKey
      remoteRef:
        key: devsecops/argocd
        property: github-privateKey

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-devsecops-store
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: github-privateKey
      remoteRef:
        key: devsecops/argocd
        property: github-privateKey
