apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-config
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: oidc.keycloak.clientSecret
    remoteRef:
      key: secrets/keycloak
      property: argocd-client-secret
