apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: eso
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 1.0.0
      helm:
        skipCrds: true
        releaseName: external-secrets
        valueFiles:
          - $values/security/eso/helm/values.yaml
        parameters:
          - name: installCRDs
            value: "false"
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard-on-prem.git
      path: security/eso/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - eso-crds

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-crds
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: eso
  sources:
    - repoURL: https://github.com/external-secrets/external-secrets.git
      path: config/crds/bases
      targetRevision: v1.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
